
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizadorLexico;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int SHOW = 13;
  public static final int OP_MAYOR = 29;
  public static final int P_Y_C = 39;
  public static final int A_PARENT = 35;
  public static final int DOUBLE = 16;
  public static final int INTEGER = 15;
  public static final int OP_MAYOR_IG = 30;
  public static final int REPEAT = 10;
  public static final int OP_MULTI = 21;
  public static final int C_LLAVE = 38;
  public static final int A_LLAVE = 37;
  public static final int OP_DIV = 22;
  public static final int C_PARENT = 36;
  public static final int ENDDECVAR = 7;
  public static final int CTE_H = 45;
  public static final int BEGIN = 17;
  public static final int CTE_F = 42;
  public static final int CTE_E = 41;
  public static final int OPL_OR = 24;
  public static final int IF = 2;
  public static final int ID = 46;
  public static final int CTE_B = 44;
  public static final int STRVAR = 11;
  public static final int EOF = 0;
  public static final int OP_MENOR_IG = 31;
  public static final int error = 1;
  public static final int COMA = 40;
  public static final int OP_DECLARACION = 33;
  public static final int NUMVAR = 12;
  public static final int OP_RESTA = 20;
  public static final int OP_ASIGNACION = 32;
  public static final int DECVAR = 6;
  public static final int ELSE = 3;
  public static final int OP_IGUAL = 27;
  public static final int CTE_STR = 43;
  public static final int WHILE = 5;
  public static final int THEN = 4;
  public static final int PROGRAM_SECTION = 8;
  public static final int END = 18;
  public static final int STRING = 14;
  public static final int IF_UNARIO = 34;
  public static final int ENDPROGRAM_SECTION = 9;
  public static final int OP_SUMA = 19;
  public static final int OP_DIST = 26;
  public static final int OPL_NOT = 25;
  public static final int OPL_AND = 23;
  public static final int OP_MENOR = 28;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "IF",
  "ELSE",
  "THEN",
  "WHILE",
  "DECVAR",
  "ENDDECVAR",
  "PROGRAM_SECTION",
  "ENDPROGRAM_SECTION",
  "REPEAT",
  "STRVAR",
  "NUMVAR",
  "SHOW",
  "STRING",
  "INTEGER",
  "DOUBLE",
  "BEGIN",
  "END",
  "OP_SUMA",
  "OP_RESTA",
  "OP_MULTI",
  "OP_DIV",
  "OPL_AND",
  "OPL_OR",
  "OPL_NOT",
  "OP_DIST",
  "OP_IGUAL",
  "OP_MENOR",
  "OP_MAYOR",
  "OP_MAYOR_IG",
  "OP_MENOR_IG",
  "OP_ASIGNACION",
  "OP_DECLARACION",
  "IF_UNARIO",
  "A_PARENT",
  "C_PARENT",
  "A_LLAVE",
  "C_LLAVE",
  "P_Y_C",
  "COMA",
  "CTE_E",
  "CTE_F",
  "CTE_STR",
  "CTE_B",
  "CTE_H",
  "ID"
  };
}

